<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-07-14T12:02:03 CEST" name="Suite" finished-at="2022-07-14T12:02:15 CEST" duration-ms="12230">
    <groups>
    </groups>
    <test started-at="2022-07-14T12:02:03 CEST" name="Test" finished-at="2022-07-14T12:02:15 CEST" duration-ms="12230">
      <class name="Rest.restcountriesComTestSuite">
        <test-method signature="SoapTest()[pri:0, instance:Rest.restcountriesComTestSuite@46d59067]" started-at="2022-07-14T12:02:11 CEST" name="SoapTest" finished-at="2022-07-14T12:02:12 CEST" duration-ms="1398" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SoapTest -->
      </class> <!-- Rest.restcountriesComTestSuite -->
      <class name="soap.testSeperatly">
        <test-method signature="singleTest()[pri:0, instance:soap.testSeperatly@2d0399f4]" started-at="2022-07-14T12:02:12 CEST" name="singleTest" finished-at="2022-07-14T12:02:13 CEST" duration-ms="568" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- singleTest -->
      </class> <!-- soap.testSeperatly -->
      <class name="soap.MultipleTestSuite">
        <test-method signature="SoapTest()[pri:0, instance:soap.MultipleTestSuite@d23e042]" started-at="2022-07-14T12:02:03 CEST" name="SoapTest" finished-at="2022-07-14T12:02:11 CEST" duration-ms="8416" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [FAILED] but found [FINISHED]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [FAILED] but found [FINISHED]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at soap.MultipleTestSuite.SoapTest(MultipleTestSuite.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SoapTest -->
      </class> <!-- soap.MultipleTestSuite -->
      <class name="soap.FirstTest">
        <test-method signature="SoapTest()[pri:0, instance:soap.FirstTest@14dd7b39]" started-at="2022-07-14T12:02:13 CEST" name="SoapTest" finished-at="2022-07-14T12:02:15 CEST" duration-ms="1799" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SoapTest -->
      </class> <!-- soap.FirstTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
